import {reconcileComments} from './contentValidation';
import {useState} from 'react';
import type {Creator} from './domain';
import type {CommentEvidence,CreatorPost} from './creatorContent';
import {registerPost} from './creatorContent';
import {normalizeWebUrl,validDate,parseMetric} from './campaign';
import {RequiredMark} from './ui';
export function ContentEntry({creator,onDone,onCancel}:{creator:Creator;onDone:()=>void;onCancel:()=>void}){
 const [title,setTitle]=useState(''),[caption,setCaption]=useState(''),[url,setUrl]=useState(''),[date,setDate]=useState(''),[kind,setKind]=useState<CreatorPost['kind']>('organic'),[brand,setBrand]=useState(''),[views,setViews]=useState(''),[rawComments,setRawComments]=useState(''),[comments,setComments]=useState<CommentEvidence[]>([]),[error,setError]=useState('');
 const save=()=>{setError('');if(!title.trim()||!caption.trim()||!validDate(date)){setError('제목, 캡션, 게시일을 확인해 주세요.');return;}const safe=normalizeWebUrl(url);if(url&&!safe){setError('게시물 주소를 확인해 주세요.');return;}const n=parseMetric(views);if(n!==null&&(!Number.isSafeInteger(n)||n<0)){setError('조회수는 0 이상의 정수로 입력해 주세요.');return;}try{registerPost(creator,{id:crypto.randomUUID(),title:title.trim(),caption:caption.trim(),date,kind,brand:kind==='ad'?brand.trim()||undefined:undefined,url:safe||undefined,views:n,likes:null,commentCount:null,comments:reconcileComments(rawComments,comments),visualTags:[],format:creator.platform==='유튜브'?'영상':'게시물'});onDone();}catch(err){setError(err instanceof Error&&err.name==='Error'?err.message:'자료를 저장하지 못했어요. 브라우저의 저장 공간을 확인해 주세요. 입력 내용은 유지됩니다.');}};
 return <form className="content-entry" onSubmit={e=>{e.preventDefault();save();}}><h3>분석할 콘텐츠 자료 추가</h3><p>게시물의 캡션과 댓글을 붙여넣으세요. 등록한 자료는 모든 캠페인에서 이 후보를 검토할 때 사용합니다.</p><div className="entry-grid"><label className="field-label"><span>콘텐츠 제목<RequiredMark/></span><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={180} required/></label><label className="field-label"><span>게시일<RequiredMark/></span><input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label className="field-label"><span>게시물 주소</span><input maxLength={3000} value={url} onChange={e=>setUrl(e.target.value)} placeholder="instagram.com/p/…"/></label><label className="field-label"><span>조회수</span><input value={views} onChange={e=>setViews(e.target.value)} inputMode="numeric" placeholder="확인한 경우에만 입력"/></label><label className="field-label"><span>콘텐츠 종류</span><select value={kind} onChange={e=>setKind(e.target.value as CreatorPost['kind'])}><option value="organic">일반 콘텐츠</option><option value="ad">광고 콘텐츠</option></select></label>{kind==='ad'&&<label className="field-label"><span>협업 브랜드</span><input maxLength={180} value={brand} onChange={e=>setBrand(e.target.value)} placeholder="게시물에서 확인한 브랜드"/></label>}</div><label className="field-label"><span>캡션·콘텐츠 내용<RequiredMark/></span><textarea value={caption} onChange={e=>setCaption(e.target.value)} maxLength={5000} required/></label><label className="field-label"><span>댓글 가져오기 · 한 줄에 하나씩</span><textarea value={rawComments} onChange={e=>setRawComments(e.target.value)} maxLength={8000} placeholder="개인정보를 제외한 댓글 내용만 붙여넣으세요."/></label><button type="button" className="secondary-button" onClick={()=>setComments(reconcileComments(rawComments,comments))}>댓글 분류 확인</button>{comments.length>0&&<div className="comment-review"><p>확인한 댓글만 반응 통계에 반영됩니다.</p>{comments.map((c,i)=><div key={i}><p>{c.text}</p><select aria-label={`${i+1}번 댓글 반응`} value={c.sentiment} onChange={e=>setComments(cs=>cs.map((x,j)=>i===j?{...x,sentiment:e.target.value as CommentEvidence['sentiment']}:x))}><option value="unreviewed">미확인</option><option value="positive">긍정</option><option value="neutral">중립</option><option value="negative">부정</option></select><label><input type="checkbox" checked={c.productQuestion} onChange={e=>setComments(cs=>cs.map((x,j)=>i===j?{...x,productQuestion:e.target.checked}:x))}/>제품 질문</label><label><input type="checkbox" checked={c.purchaseIntent} onChange={e=>setComments(cs=>cs.map((x,j)=>i===j?{...x,purchaseIntent:e.target.checked}:x))}/>구매 의향</label></div>)}</div>}<p className="data-caption">이 후보에 자료를 처음 등록하면, 별도 예시 자료 대신 등록한 자료만 분석합니다.</p>{error&&<p className="error-text" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="secondary-button" onClick={onCancel}>취소</button><button type="submit" className="primary-button">저장하고 분석 보기</button></div></form>;
}
