import {requestResearch} from './researchAI';
import {readVisualReference} from './visualSearch';
import type {VisualReference} from './visualSearch';
import {useEffect,useRef,useState} from 'react';
import type {Campaign} from './campaign';
import {cleanKeywords} from './creatorContent';
import {searchDraft,suggestKeywords} from './discovery';
import {Icon} from './ui';

export function KeywordField({label,value,onChange,suggestions=[]}:{label:string;value:string[];onChange:(value:string[])=>void;suggestions?:string[]}){
 const [input,setInput]=useState('');
 const add=()=>{if(input.trim()){onChange(cleanKeywords([...value,...input.split(/[,\n]/)]));setInput('');}};
 return <div className="keyword-field"><label>{label}<div className="keyword-input">{value.map(k=><button type="button" key={k} onClick={()=>onChange(value.filter(x=>x!==k))} aria-label={`${label} ${k} 삭제`}>{k}<span>×</span></button>)}<input value={input} maxLength={120} placeholder="키워드 입력 후 Enter" onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing){e.preventDefault();add();}}} onBlur={add}/></div></label>{suggestions.filter(k=>!value.includes(k)).length>0&&<div className="keyword-suggestions"><span>추천</span>{suggestions.filter(k=>!value.includes(k)).slice(0,5).map(k=><button type="button" key={k} onClick={()=>onChange(cleanKeywords([...value,k]))}>+ {k}</button>)}</div>}</div>;
}
export function DiscoverySearch({campaign,onApply}:{campaign:Campaign;onApply:(c:Campaign)=>void}){
 const [text,setText]=useState(campaign.searchText??''),[draft,setDraft]=useState(campaign),[busy,setBusy]=useState(false),[review,setReview]=useState(false);
 const controller=useRef<AbortController|null>(null);
 const [reference,setReference]=useState<VisualReference|null>(null),[imageError,setImageError]=useState('');
 const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{setDraft(campaign);setText(campaign.searchText??'');},[campaign]);
 useEffect(()=>()=>controller.current?.abort(),[]);
 const search=async()=>{controller.current?.abort();const request=new AbortController();controller.current=request;setBusy(true);setImageError('');try{const live=await requestResearch({task:'search',text,context:JSON.stringify(campaign),image:reference?.preview},request.signal);if(request.signal.aborted)return;const next=text.trim()?searchDraft(text,campaign):{...campaign,includeKeywords:[]};setDraft({...next,includeKeywords:cleanKeywords(live?.keywords??[...(next.includeKeywords??[]),...(reference?.tags??[])]),excludeKeywords:cleanKeywords(live?.excludeKeywords??next.excludeKeywords??[])});setReview(true);}catch(err){if(!request.signal.aborted)setImageError(err instanceof Error?err.message:'조건을 다시 확인해 주세요.');}finally{if(!request.signal.aborted)setBusy(false);}};
 return <section className="discovery-search" aria-label="AI 크리에이터 검색"><div className="search-caption"><span>✦ AI Search</span><small>소개·콘텐츠에서 원하는 특징을 찾아보세요</small></div><div className="search-composer"><Icon name="search" size={21}/><input aria-label="찾고 싶은 크리에이터" value={text} maxLength={600} placeholder="예: 출근룩을 소개하는 미니멀 패션 크리에이터, 화려한 스타일은 제외" onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing&&text.trim())search();}}/><button className="primary-button" disabled={busy||(!text.trim()&&!reference)} onClick={search}>{busy?'조건 정리 중':'검색 조건 만들기'}<Icon name="arrow" size={16}/></button></div>
 <div className="image-search-row"><input ref={file} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setImageError('');try{setReference(await readVisualReference(f));}catch(err){setImageError(err instanceof Error?err.message:'이미지를 확인해 주세요.');}e.target.value='';}}/><button className="image-upload-button" onClick={()=>file.current?.click()}><Icon name="views" size={14}/> 참고 이미지</button>{reference&&<div className="reference-thumb"><img src={reference.preview} alt="검색에 참고할 이미지"/><span>{reference.description}<small>색감에서 찾은 키워드 · {reference.tags.join(' · ')}</small></span><button onClick={()=>setReference(null)} aria-label="참고 이미지 제거">×</button></div>}{imageError&&<span className="error-text" role="alert">{imageError}</span>}</div><div className="search-filterbar"><div className="platform-filters">{['','인스타그램','유튜브'].map(p=><button key={p} aria-pressed={(campaign.searchPlatform??'')===p} onClick={()=>onApply({...campaign,searchPlatform:p})}>{p&&<Icon name={p==='유튜브'?'youtube':'instagram'} size={15}/>} {p||'모든 채널'}</button>)}</div><button className="text-button" onClick={()=>setReview(!review)}>포함·제외 키워드 {(campaign.includeKeywords?.length??0)+(campaign.excludeKeywords?.length??0)>0?`(${(campaign.includeKeywords?.length??0)+(campaign.excludeKeywords?.length??0)})`:''}</button></div>
 {review&&<div className="search-review"><h3>찾을 조건을 확인해 주세요</h3><div className="keyword-pair"><KeywordField label="포함할 키워드" value={draft.includeKeywords??[]} suggestions={suggestKeywords(campaign.product+' '+text)} onChange={includeKeywords=>setDraft({...draft,includeKeywords})}/><KeywordField label="제외할 키워드" value={draft.excludeKeywords??[]} onChange={excludeKeywords=>setDraft({...draft,excludeKeywords})}/></div><p>포함 키워드 중 하나가 소개·콘텐츠에 있고, 제외 키워드가 없는 후보를 찾습니다.</p><div className="form-actions"><button className="text-button" onClick={()=>{onApply({...campaign,includeKeywords:[],excludeKeywords:[],searchText:''});setReview(false);}}>키워드 지우기</button><button className="secondary-button" onClick={()=>{setReview(false);setDraft(campaign);}}>취소</button><button className="primary-button" onClick={()=>{onApply(draft);setReview(false);}}>이 조건 적용</button></div></div>}
 </section>;
}
