import {useEffect,useState} from 'react';
import type {Creator} from './domain';
import type {Brief,Notes} from './experience';
import {campaignOf,exampleWork,STAGES,METRICS,emptyWork,efficiencies,hasOutcome,reportSummary} from './campaign';
import type {WorkRecord,WorkRecords,Stage} from './campaign';
import {moneyText,numberText} from './policy';
import {Icon,Identity} from './ui';
import {AssistantPanel} from './AssistantPanel';
import {CollaborationEditor} from './CollaborationEditor';
import {SentInquiries} from './SentInquiries';
import {sentHistoryOf} from './sentHistory';
import {stageNeeds} from './collaborationFlow';

const metricText=(n:number|null,unit='')=>n===null?'미입력':numberText(n)+unit;
const rateText=(n:number|null,unit='원')=>n===null?'—':numberText(Math.round(n*100)/100)+unit;
const efficiencyLabels={cpv:'조회 1회당 비용',cpe:'반응 1건당 비용',cpc:'클릭 1회당 비용',cpa:'구매 1건당 비용',roas:'입력 매출 / 집행비'} as const;
export function Workflow({all,contacts,work:storedWork,brief,notes,onUpdate,onExplore,onReport,initialCreatorId,onConsumeTarget,report=false,sent=false}:{all:Creator[];contacts:Creator[];work:WorkRecords;brief:Brief;notes:Notes;onUpdate:(id:string,value:WorkRecord)=>void;onExplore:()=>void;onReport:()=>void;initialCreatorId:string|null;onConsumeTarget:()=>void;report?:boolean;sent?:boolean}){
  const [editing,setEditing]=useState<Creator|null>(null),[results,setResults]=useState(false),[history,setHistory]=useState(false),[filter,setFilter]=useState<Stage|'all'>('all'),[expanded,setExpanded]=useState<string|null>(null),[showAI,setShowAI]=useState(false);
  const [sample,setSample]=useState(false);
  useEffect(()=>{if(!initialCreatorId)return;const creator=all.find(c=>c.id===initialCreatorId);if(creator){setEditing(creator);setResults(false);setHistory(false);setSample(false);onConsumeTarget();}},[initialCreatorId,all]);
  const sampleCreator=all.find(c=>c.id==='C0066')??all[0];
  const work=sample&&sampleCreator?{[sampleCreator.id]:exampleWork()}:storedWork;
  const activeContacts=sample&&sampleCreator?[sampleCreator]:contacts;
  const people=[...new Set([...activeContacts.map(c=>c.id),...Object.keys(work)])].flatMap(id=>all.find(c=>c.id===id)??[]);
  const completed=people.filter(c=>work[c.id]&&hasOutcome(work[c.id].outcome));
  const summary=reportSummary(Object.fromEntries(people.filter(c=>work[c.id]).map(c=>[c.id,work[c.id]])));
  const open=(c:Creator,result:boolean,showSent=false)=>{if(sample)setSample(false);setEditing(c);setResults(result);setHistory(showSent);};
  const reportContext=JSON.stringify({campaign:campaignOf(brief),definition:'사용자가 직접 기록한 콘텐츠별 최신 누적 성과. 관측 기간과 출처가 달라 직접적인 성과 우열·인과 추론 불가. 원본 평균 조회수는 이번 광고 예상값이 아님.',scope:`전체 성과 기록 ${completed.length}명 중 아래 ${Math.min(completed.length,8)}명만 요약. 나머지 결과를 추정하지 말 것.`,results:completed.slice(0,8).map(c=>({name:c.name,platform:c.platform,outcome:{...work[c.id].outcome,source:work[c.id].outcome.source.slice(0,300),attribution:work[c.id].outcome.attribution.slice(0,300),contentUrl:undefined},calculated:efficiencies(work[c.id].outcome)}))},null,2);
  const showReport=()=>{setEditing(null);setResults(false);setHistory(false);setSample(false);onReport();};
  if(sent)return <><SentInquiries all={all} work={storedWork} onExplore={onExplore} onOpen={c=>open(c,false,true)}/>{editing&&<CollaborationEditor creator={editing} record={storedWork[editing.id]??emptyWork()} brief={brief} reason={notes[editing.id]??''} onSave={value=>onUpdate(editing.id,value)} onReport={showReport} onClose={()=>setEditing(null)} initialSent={history} initialResults={results}/>}</>;
  return <div className="workflow-page"><div className="page-heading"><div><p className="section-kicker">{campaignOf(brief).name} · {report?'집행 후 확인':'문의부터 집행까지'}</p><h1>{report?'성과 리포트':'협업 관리'}</h1></div>{report&&<div className="header-actions"><button className="secondary-button" onClick={()=>{setSample(!sample);setShowAI(false);setExpanded(null);}}>{sample?'내 기록으로 돌아가기':'예시 리포트 보기'}</button>{completed.length>0&&<button className="ai-button" onClick={()=>setShowAI(!showAI)}>✦ AI로 결과 정리</button>}</div>}</div><p className="workflow-intro">{report?'협업이 끝나면 조회수와 비용을 기록하세요. 어떤 협업을 다시 검토할지 판단할 수 있어요.':'보낸 문의의 답변과 협업 진행 상태를 관리하세요.'}</p>
    {report?<>{!sample&&completed.length===0&&<section className="report-welcome"><span className="section-kicker">협업 후에는 이렇게 사용해요</span><h2>어떤 협업이 잘됐는지, 함께 돌아보세요.</h2><p>크리에이터에게 받은 결과를 입력하면 비용 대비 성과를 한눈에 볼 수 있어요.</p><ol><li><strong>1</strong>협업한 후보 선택</li><li><strong>2</strong>조회수·비용 입력</li><li><strong>3</strong>결과 비교</li></ol><button className="secondary-button" onClick={()=>setSample(true)}>완성된 리포트로 먼저 살펴보기<Icon name="arrow" size={16}/></button></section>}{sample&&<div className="sample-banner"><strong>예시 리포트 · 실제 집행 결과가 아닙니다.</strong><p>화면과 계산 방식을 보여주기 위한 수치입니다. 내 협업 기록에 저장되지 않습니다.</p></div>}{completed.length>0&&<><div className="report-kpis"><div><span>성과 기록</span><strong>{summary.count}<small>명 / 협업 후보 {people.length}명</small></strong></div><div><span>조회수 합계</span><strong>{summary.viewCount?numberText(summary.views):'—'}<small>{summary.viewCount}명 입력</small></strong></div><div><span>실제 집행비 합계</span><strong>{summary.costCount?moneyText(summary.cost):'—'}<small>{summary.costCount}명 입력</small></strong></div><div><span>조회 1회당 비용</span><strong>{rateText(summary.cpv)}<small>비용·조회수가 있는 {summary.pairCount}명 기준</small></strong></div></div><p className="data-caption">입력한 콘텐츠 결과의 합계입니다. 같은 사람이 여러 콘텐츠를 봤을 수 있어요.</p></>}
      {showAI&&completed.length>0&&<><p className="data-caption">입력한 성과 중 최대 8명의 결과를 정리해요. {completed.length>8?`${completed.length-8}명의 기록은 이번 요약에서 제외됩니다.`:''}</p><AssistantPanel mode="analysis" context={reportContext}/></>}
      {people.length===0?<div className="empty-state"><h2>협업 결과를 쌓을 준비가 됐어요.</h2><p>후보에게 문의하고 협업을 시작하면, 여기서 콘텐츠별 결과를 기록할 수 있어요.</p><button className="primary-button" onClick={onExplore}>협업할 후보 찾기</button></div>:<div className="report-list">{people.map(c=>{const record=work[c.id]??emptyWork(),o=record.outcome,has=hasOutcome(o),metrics=efficiencies(o);return <section className="report-card" key={c.id}><div className="report-card-head"><Identity creator={c}/><div>{has?<button className="secondary-button" onClick={()=>setExpanded(expanded===c.id?null:c.id)}>{expanded===c.id?'상세 접기':'상세 결과 보기'}</button>:<span className="stage-badge">성과 미입력</span>}<button className="text-button" onClick={()=>open(c,true)}>{sample?'내 기록 입력하기':has?'결과 수정':'성과 기록'}</button></div></div>{has&&<><div className="report-metrics">{[['조회수',metricText(o.views,'회')],['링크 클릭',metricText(o.clicks,'회')],['구매',metricText(o.conversions,'건')],['실제 집행비',metricText(o.cost,'원')]].map(([l,v])=><div key={l}><span>{l}</span><strong>{v}</strong></div>)}</div><p className="data-caption">확인일 {o.measuredAt} · 출처: {o.source}</p></>}{expanded===c.id&&has&&<div className="report-detail"><div className="report-metrics">{METRICS.filter(m=>!['views','clicks','conversions'].includes(m.key)).map(m=><div key={m.key}><span>{m.label}</span><strong>{metricText(o[m.key],m.unit)}</strong></div>)}</div><div className="efficiency-grid">{(Object.keys(efficiencyLabels) as (keyof typeof efficiencyLabels)[]).map(k=><div key={k}><span>{efficiencyLabels[k]}</span><strong>{rateText(metrics[k],k==='roas'?'%':'원')}</strong></div>)}</div><p className="data-caption">반응당 비용은 좋아요·댓글·공유·저장을 모두 입력했을 때 계산합니다. ‘—’는 계산에 필요한 값이 없거나 분모가 0인 경우입니다.</p>{o.attribution&&<p>구매·매출 집계 기준: {o.attribution}</p>}{o.contentUrl&&<a className="text-button" target="_blank" rel="noreferrer" href={o.contentUrl}>집행 콘텐츠 열기 ↗</a>}<div className="reference-note">참고 · 원본 채널 평균 조회수 {numberText(c.views)}회, 참여율 {c.engagement}%. 이번 콘텐츠와 측정 대상·기간이 달라 증감률을 계산하지 않습니다.</div></div>}</section>;})}</div>}
    </>:<><div className="pipeline-steps"><span>1 문의 준비</span><Icon name="arrow" size={16}/><span>2 답변·조건 협의</span><Icon name="arrow" size={16}/><span>3 제작 진행</span><Icon name="arrow" size={16}/><span>4 성과 기록</span></div><div className="stage-filters" role="group" aria-label="협업 상태 필터"><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>전체 {people.length}</button>{STAGES.map(s=><button key={s.id} aria-pressed={filter===s.id} onClick={()=>setFilter(s.id)}>{s.label} {people.filter(c=>(work[c.id]?.stage??'draft')===s.id).length}</button>)}</div>{people.length===0?<div className="empty-state"><h2>먼저 문의할 후보를 정해주세요.</h2><p>후보 상세나 비교 화면에서 ‘문의하기’를 누르면 문안을 준비할 수 있어요.</p><button className="primary-button" onClick={onExplore}>후보 살펴보기</button></div>:people.filter(c=>filter==='all'||(work[c.id]?.stage??'draft')===filter).length===0?<div className="empty-state"><h2>이 상태의 협업은 없어요.</h2><button className="secondary-button" onClick={()=>setFilter('all')}>전체 협업 보기</button></div>:<div className="pipeline-list">{people.filter(c=>filter==='all'||(work[c.id]?.stage??'draft')===filter).map(c=>{const w=work[c.id]??emptyWork(),stage=STAGES.find(s=>s.id===w.stage)!;return <article key={c.id} className="pipeline-row"><Identity creator={c}/><div><select className={'pipeline-stage '+w.stage} aria-label={c.name+' 진행 상태'} value={w.stage} onChange={e=>onUpdate(c.id,{...w,stage:e.target.value as Stage})}>{STAGES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><small>{w.contactedAt?'문의 '+w.contactedAt:w.demoSentAt?'문의 보냄':w.stage==='draft'?'아직 연락 전':'문의 날짜 미입력'}</small></div><div className="pipeline-terms"><strong>{w.agreedCost!==null?'합의 '+moneyText(w.agreedCost):w.quotedCost!==null?'견적 '+moneyText(w.quotedCost):'견적 미입력'}</strong><small>{w.deliverable||'제작 범위 미정'}</small>{stageNeeds(w).length>0&&<small>{stageNeeds(w).length}개 항목 추가 가능</small>}</div><div className="pipeline-actions">{sentHistoryOf(w).length>0&&<button className="text-button" onClick={()=>open(c,false,true)}>보낸 문의 {sentHistoryOf(w).length}건</button>}<button className="secondary-button" onClick={()=>open(c,w.stage==='complete')}>{stage.next}<Icon name="arrow" size={16}/></button></div></article>;})}</div>}<div className="workflow-note"><strong>상태는 목록에서 바로 바꿀 수 있어요.</strong><p>견적과 일정은 후보 옆 버튼을 눌러 입력하세요. 상태를 바꾸어도 이미 기록한 조건과 성과는 유지됩니다.</p></div></>}
    {editing&&<CollaborationEditor creator={editing} record={work[editing.id]??emptyWork()} brief={brief} reason={notes[editing.id]??''} onSave={value=>onUpdate(editing.id,value)} onReport={showReport} onClose={()=>setEditing(null)} initialResults={results} initialSent={history}/>}
  </div>;
}
