import {useEffect,useState} from 'react';
import type {Creator} from './domain';
import type {Brief,Notes} from './experience';
import {formatBudget} from './experience';
import {campaignOf,exampleWork,STAGES,METRICS,emptyWork,efficiencies,hasOutcome,inquiryDraft,parseMetric,reportSummary,workErrors} from './campaign';
import type {WorkRecord,WorkRecords,Outcome,Stage} from './campaign';
import {moneyText,numberText} from './policy';
import {Icon,Identity,Modal} from './ui';
import {AssistantPanel} from './AssistantPanel';

const metricText=(n:number|null,unit='')=>n===null?'미입력':numberText(n)+unit;
const rateText=(n:number|null,unit='원')=>n===null?'—':numberText(Math.round(n*100)/100)+unit;
const efficiencyLabels={cpv:'조회 1회당 비용',cpe:'반응 1건당 비용',cpc:'클릭 1회당 비용',cpa:'구매 1건당 비용',roas:'입력 매출 / 집행비'} as const;
function AmountField({label,value,onChange}:{label:string;value:number|null;onChange:(value:number|null)=>void}){
  const [raw,setRaw]=useState(value===null?'':numberText(value));
  return <label className="field-label">{label}<input inputMode="numeric" placeholder="모르면 비워두세요" value={raw} onChange={e=>{const text=formatBudget(e.target.value);setRaw(text);onChange(parseMetric(text));}}/></label>;
}
function OutcomeFields({value,onChange}:{value:Outcome;onChange:(value:Outcome)=>void}){
  return <div className="outcome-fields"><div className="section-heading"><div><h3>이번 콘텐츠의 집행 결과</h3><p>확인한 수치만 입력하세요. 같은 콘텐츠의 누적 결과로 업데이트합니다.</p></div><span className="manual-badge">직접 입력</span></div><div className="field-grid"><label className="field-label">콘텐츠 링크<input type="url" value={value.contentUrl} placeholder="https://…" onChange={e=>onChange({...value,contentUrl:e.target.value})}/></label><label className="field-label">성과 확인일<input type="date" onInput={e=>onChange({...value,measuredAt:e.currentTarget.value})} value={value.measuredAt} onChange={e=>onChange({...value,measuredAt:e.target.value})}/></label><label className="field-label span-two">출처<input value={value.source} maxLength={1000} placeholder="예: 크리에이터가 전달한 인사이트 캡처, 관리자 화면" onChange={e=>onChange({...value,source:e.target.value})}/></label><AmountField label="실제 집행비 (원)" value={value.cost} onChange={cost=>onChange({...value,cost})}/>{METRICS.map(m=><AmountField key={m.key} label={m.label+' ('+m.unit+')'} value={value[m.key]} onChange={n=>onChange({...value,[m.key]:n})}/>)}</div><label className="field-label">구매·매출 집계 기준<input maxLength={1000} value={value.attribution} placeholder="예: 전용 할인코드 사용 구매, 게시 후 7일 집계" onChange={e=>onChange({...value,attribution:e.target.value})}/></label><p className="muted">채널별 지표 정의와 집계 기간이 다를 수 있습니다. 여러 콘텐츠 합산과 중복 구매 제거는 이 체험 범위에 포함하지 않습니다.</p></div>;
}
function RecordEditor({creator:c,record,brief,reason,onSave,onClose,initialResults=false}:{creator:Creator;record:WorkRecord;brief:Brief;reason:string;onSave:(record:WorkRecord)=>void;onClose:()=>void;initialResults?:boolean}){
  const [draft,setDraft]=useState(record),[section,setSection]=useState<'contact'|'result'>(initialResults?'result':'contact'),[errors,setErrors]=useState<string[]>([]),[copied,setCopied]=useState(''),[showAI,setShowAI]=useState(false);
  useEffect(()=>setErrors([]),[draft]);
  const text=draft.message||inquiryDraft(c,brief,draft,reason);
  const save=()=>{const errors=workErrors(draft);setErrors(errors);if(!errors.length)onSave(draft);};
  return <Modal title={c.name+' · 협업 기록'} onClose={onClose} wide><div className="workflow-editor"><div className="editor-summary"><Identity creator={c}/><span className={'stage-badge '+draft.stage}>{STAGES.find(s=>s.id===draft.stage)?.label}</span></div><div className="editor-tabs" role="tablist" aria-label="협업 기록 영역"><button role="tab" aria-selected={section==='contact'} onClick={()=>setSection('contact')}>문의·진행 기록</button><button role="tab" aria-selected={section==='result'} onClick={()=>setSection('result')}>콘텐츠·성과</button></div>
    {section==='contact'?<><div className="contact-steps">문안을 준비한 뒤 메일이나 DM으로 보내고, 받은 답변을 기록하세요.</div><section className="inquiry-draft"><div className="section-heading"><div><h3>보낼 문의 문안</h3><p>제품과 예산을 미리 채웠어요. 제작 범위와 일정을 확인한 뒤 보내세요.</p></div><button className="ai-button" onClick={()=>setShowAI(!showAI)}>✦ AI로 다듬기</button></div><textarea aria-label="보낼 문의 문안" value={text} onChange={e=>setDraft({...draft,message:e.target.value})}/><div className="form-actions"><button className="text-button" onClick={()=>setDraft({...draft,message:''})}>현재 조건으로 다시 채우기</button><button className="secondary-button" onClick={async()=>{try{await navigator.clipboard.writeText(text);setCopied('복사했어요. 실제 채널이나 메일에서 보내고, 문의 날짜와 진행 상태를 기록하세요.');}catch{setCopied('자동 복사가 제한되어 있어요. 문안을 직접 선택해 복사해 주세요.');}}}>문의 문안 복사</button>{draft.email&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.email)&&<a className="primary-button" href={'mailto:'+encodeURIComponent(draft.email)+'?subject='+encodeURIComponent(campaignOf(brief).name+' 협업 문의')+'&body='+encodeURIComponent(text)}>이메일 초안 열기</a>}</div><p role="status" className="copy-status">{copied||'1 문안 확인 → 2 메일·DM으로 문의 → 3 답변과 견적 기록'}</p></section>
    {showAI&&<AssistantPanel mode="outreach" context={text} onApply={value=>{setDraft({...draft,message:value});setShowAI(false);setCopied('AI 문안을 적용했습니다. 내용 확인 후 직접 보내세요.');}}/>}<details className="contact-details"><summary>제작 조건·연락처·진행 상태 편집</summary><div className="field-grid"><label className="field-label">진행 상태<select value={draft.stage} onChange={e=>setDraft({...draft,stage:e.target.value as Stage})}>{STAGES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label className="field-label">실제로 문의한 날짜<input type="date" onInput={e=>setDraft({...draft,contactedAt:e.currentTarget.value})} value={draft.contactedAt} onChange={e=>setDraft({...draft,contactedAt:e.target.value})}/></label><label className="field-label">확인한 채널 링크<input type="url" value={draft.channelUrl} maxLength={1000} placeholder="https://…" onChange={e=>setDraft({...draft,channelUrl:e.target.value})}/></label><label className="field-label">확인한 이메일<input type="email" value={draft.email} maxLength={254} placeholder="직접 확인한 연락처 입력" onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label className="field-label">제작 범위<input maxLength={500} value={draft.deliverable} placeholder="예: 릴스 1편, 수정 1회" onChange={e=>setDraft({...draft,deliverable:e.target.value})}/></label><label className="field-label">게시 예정일<input type="date" onInput={e=>setDraft({...draft,dueDate:e.currentTarget.value})} value={draft.dueDate} onChange={e=>setDraft({...draft,dueDate:e.target.value})}/></label><label className="field-label">콘텐츠 사용권<input value={draft.rights} maxLength={500} placeholder="예: 브랜드 채널 재게시 30일" onChange={e=>setDraft({...draft,rights:e.target.value})}/></label><AmountField label="합의 비용 (원)" value={draft.agreedCost} onChange={agreedCost=>setDraft({...draft,agreedCost})}/></div><p className="muted">메일로 문의하려면 연락처를 입력하세요. DM으로 문의할 때는 문안을 복사해 사용하세요.</p>
    </details><label className="field-label">답변·협의 메모<textarea value={draft.memo} maxLength={2000} placeholder="답변 내용과 다음에 확인할 사항을 기록하세요." onChange={e=>setDraft({...draft,memo:e.target.value})}/></label></>:<OutcomeFields value={draft.outcome} onChange={outcome=>setDraft({...draft,outcome})}/>}
    {errors.length>0&&<ul className="error-box" role="alert">{errors.map(e=><li key={e}>{e}</li>)}</ul>}<div className="editor-footer"><p>보낸 뒤 진행 상태를 ‘답변 대기’로 바꿔주세요.</p><button className="primary-button" onClick={save}>협업 기록 저장<Icon name="check" size={16}/></button></div></div></Modal>;
}
export function Workflow({all,contacts,work:storedWork,brief,notes,onUpdate,onExplore,report=false}:{all:Creator[];contacts:Creator[];work:WorkRecords;brief:Brief;notes:Notes;onUpdate:(id:string,value:WorkRecord)=>void;onExplore:()=>void;report?:boolean}){
  const [editing,setEditing]=useState<Creator|null>(null),[results,setResults]=useState(false),[filter,setFilter]=useState<Stage|'all'>('all'),[expanded,setExpanded]=useState<string|null>(null),[showAI,setShowAI]=useState(false);
  const [sample,setSample]=useState(false);
  const sampleCreator=all.find(c=>c.id==='C0066')??all[0];
  const work=sample&&sampleCreator?{[sampleCreator.id]:exampleWork()}:storedWork;
  const activeContacts=sample&&sampleCreator?[sampleCreator]:contacts;
  const people=[...new Set([...activeContacts.map(c=>c.id),...Object.keys(work)])].flatMap(id=>all.find(c=>c.id===id)??[]);
  const completed=people.filter(c=>work[c.id]&&hasOutcome(work[c.id].outcome));
  const summary=reportSummary(Object.fromEntries(people.filter(c=>work[c.id]).map(c=>[c.id,work[c.id]])));
  const open=(c:Creator,result:boolean)=>{if(sample)setSample(false);setEditing(c);setResults(result);};
  const reportContext=JSON.stringify({campaign:campaignOf(brief),definition:'사용자가 직접 기록한 콘텐츠별 최신 누적 성과. 관측 기간과 출처가 달라 직접적인 성과 우열·인과 추론 불가. 원본 평균 조회수는 이번 광고 예상값이 아님.',scope:`전체 성과 기록 ${completed.length}명 중 아래 ${Math.min(completed.length,8)}명만 요약. 나머지 결과를 추정하지 말 것.`,results:completed.slice(0,8).map(c=>({name:c.name,platform:c.platform,outcome:{...work[c.id].outcome,source:work[c.id].outcome.source.slice(0,300),attribution:work[c.id].outcome.attribution.slice(0,300),contentUrl:undefined},calculated:efficiencies(work[c.id].outcome)}))},null,2);
  return <div className="workflow-page"><div className="page-heading"><div><p className="section-kicker">{campaignOf(brief).name} · {report?'집행 후 확인':'문의부터 집행까지'}</p><h1>{report?'성과 리포트':'협업 관리'}</h1></div>{report&&<div className="header-actions"><button className="secondary-button" onClick={()=>{setSample(!sample);setShowAI(false);setExpanded(null);}}>{sample?'내 기록으로 돌아가기':'예시 리포트 보기'}</button>{completed.length>0&&<button className="ai-button" onClick={()=>setShowAI(!showAI)}>✦ AI로 결과 정리</button>}</div>}</div><p className="workflow-intro">{report?'협업이 끝나면 조회수와 비용을 기록하세요. 어떤 협업을 다시 검토할지 판단할 수 있어요.':'문의 후보의 연락과 진행 상태를 한곳에서 이어가세요.'}</p>
    {report?<>{!sample&&completed.length===0&&<section className="report-welcome"><span className="section-kicker">협업 후에는 이렇게 사용해요</span><h2>어떤 협업이 잘됐는지, 함께 돌아보세요.</h2><p>크리에이터에게 받은 결과를 입력하면 비용 대비 성과를 한눈에 볼 수 있어요.</p><ol><li><strong>1</strong>협업한 후보 선택</li><li><strong>2</strong>조회수·비용 입력</li><li><strong>3</strong>결과 비교·팀 공유</li></ol><button className="secondary-button" onClick={()=>setSample(true)}>완성된 리포트로 먼저 살펴보기<Icon name="arrow" size={16}/></button></section>}{sample&&<div className="sample-banner"><strong>예시 리포트 · 실제 집행 결과가 아닙니다.</strong><p>화면과 계산 방식을 보여주기 위한 수치입니다. 내 협업 기록에 저장되지 않습니다.</p></div>}{completed.length>0&&<><div className="report-kpis"><div><span>성과 기록</span><strong>{summary.count}<small>명 / 협업 후보 {people.length}명</small></strong></div><div><span>조회수 합계</span><strong>{summary.viewCount?numberText(summary.views):'—'}<small>{summary.viewCount}명 입력</small></strong></div><div><span>실제 집행비 합계</span><strong>{summary.costCount?moneyText(summary.cost):'—'}<small>{summary.costCount}명 입력</small></strong></div><div><span>조회 1회당 비용</span><strong>{rateText(summary.cpv)}<small>비용·조회수가 있는 {summary.pairCount}명 기준</small></strong></div></div><p className="data-caption">입력한 콘텐츠 결과의 합계입니다. 같은 사람이 여러 콘텐츠를 봤을 수 있어요.</p></>}
      {showAI&&completed.length>0&&<><p className="data-caption">입력한 성과 중 최대 8명의 결과를 정리해요. {completed.length>8?`${completed.length-8}명의 기록은 이번 요약에서 제외됩니다.`:''}</p><AssistantPanel mode="analysis" context={reportContext}/></>}
      {people.length===0?<div className="empty-state"><h2>협업 결과를 쌓을 준비가 됐어요.</h2><p>후보를 살펴보고 문의 후보로 지정하면, 여기서 콘텐츠별 결과를 기록할 수 있습니다.</p><button className="primary-button" onClick={onExplore}>협업할 후보 찾기</button></div>:<div className="report-list">{people.map(c=>{const record=work[c.id]??emptyWork(),o=record.outcome,has=hasOutcome(o),metrics=efficiencies(o);return <section className="report-card" key={c.id}><div className="report-card-head"><Identity creator={c}/><div>{has?<button className="secondary-button" onClick={()=>setExpanded(expanded===c.id?null:c.id)}>{expanded===c.id?'상세 접기':'상세 결과 보기'}</button>:<span className="stage-badge">성과 미입력</span>}<button className="text-button" onClick={()=>open(c,true)}>{sample?'내 기록 입력하기':has?'결과 수정':'성과 기록'}</button></div></div>{has&&<><div className="report-metrics">{[['조회수',metricText(o.views,'회')],['링크 클릭',metricText(o.clicks,'회')],['구매',metricText(o.conversions,'건')],['실제 집행비',metricText(o.cost,'원')]].map(([l,v])=><div key={l}><span>{l}</span><strong>{v}</strong></div>)}</div><p className="data-caption">확인일 {o.measuredAt} · 출처: {o.source}</p></>}{expanded===c.id&&has&&<div className="report-detail"><div className="report-metrics">{METRICS.filter(m=>!['views','clicks','conversions'].includes(m.key)).map(m=><div key={m.key}><span>{m.label}</span><strong>{metricText(o[m.key],m.unit)}</strong></div>)}</div><div className="efficiency-grid">{(Object.keys(efficiencyLabels) as (keyof typeof efficiencyLabels)[]).map(k=><div key={k}><span>{efficiencyLabels[k]}</span><strong>{rateText(metrics[k],k==='roas'?'%':'원')}</strong></div>)}</div><p className="data-caption">반응당 비용은 좋아요·댓글·공유·저장을 모두 입력했을 때 계산합니다. ‘—’는 계산에 필요한 값이 없거나 분모가 0인 경우입니다.</p>{o.attribution&&<p>구매·매출 집계 기준: {o.attribution}</p>}{o.contentUrl&&<a className="text-button" target="_blank" rel="noreferrer" href={o.contentUrl}>집행 콘텐츠 열기 ↗</a>}<div className="reference-note">참고 · 원본 채널 평균 조회수 {numberText(c.views)}회, 참여율 {c.engagement}%. 이번 콘텐츠와 측정 대상·기간이 달라 증감률을 계산하지 않습니다.</div></div>}</section>;})}</div>}
    </>:<><div className="pipeline-steps"><span>1 문의 준비</span><Icon name="arrow" size={16}/><span>2 답변·조건 협의</span><Icon name="arrow" size={16}/><span>3 제작 진행</span><Icon name="arrow" size={16}/><span>4 성과 기록</span></div><div className="stage-filters" role="group" aria-label="협업 상태 필터"><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>전체 {people.length}</button>{STAGES.map(s=><button key={s.id} aria-pressed={filter===s.id} onClick={()=>setFilter(s.id)}>{s.label} {people.filter(c=>(work[c.id]?.stage??'draft')===s.id).length}</button>)}</div>{people.length===0?<div className="empty-state"><h2>먼저 문의할 후보를 정해주세요.</h2><p>후보 상세나 비교 화면에서 ‘문의 후보’로 지정하면 이어서 문안을 준비할 수 있어요.</p><button className="primary-button" onClick={onExplore}>후보 살펴보기</button></div>:people.filter(c=>filter==='all'||(work[c.id]?.stage??'draft')===filter).length===0?<div className="empty-state"><h2>이 상태의 협업은 없어요.</h2><button className="secondary-button" onClick={()=>setFilter('all')}>전체 협업 보기</button></div>:<div className="pipeline-list">{people.filter(c=>filter==='all'||(work[c.id]?.stage??'draft')===filter).map(c=>{const w=work[c.id]??emptyWork(),stage=STAGES.find(s=>s.id===w.stage)!;return <article key={c.id} className="pipeline-row"><Identity creator={c}/><div><span className={'stage-badge '+w.stage}>{stage.label}</span><small>{w.contactedAt?'문의 '+w.contactedAt:'아직 연락 전'}</small></div><div className="pipeline-terms"><strong>{w.agreedCost===null?'견적 협의 전':moneyText(w.agreedCost)}</strong><small>{w.deliverable||'제작 범위 미정'}</small></div><button className="secondary-button" onClick={()=>open(c,['active','complete'].includes(w.stage))}>{stage.next}<Icon name="arrow" size={16}/></button></article>;})}</div>}<div className="workflow-note"><strong>견적을 받았나요? 다음 단계로 옮겨보세요.</strong><p>후보 옆 버튼을 눌러 답변과 견적을 기록하세요. 제작을 마치면 같은 화면에서 콘텐츠 성과를 남길 수 있어요.</p></div></>}
    {editing&&<RecordEditor creator={editing} record={work[editing.id]??emptyWork()} brief={brief} reason={notes[editing.id]??''} onSave={value=>{onUpdate(editing.id,value);setEditing(null);}} onClose={()=>setEditing(null)} initialResults={results}/>}
  </div>;
}
